-- ============================================================
-- V4 Daily Task Reports Migration
-- Run this in your Supabase SQL editor
-- Creates the daily_task_reports table for end-of-day snapshots
-- ============================================================

-- ============================================================
-- TABLE: daily_task_reports
-- Stores a daily snapshot of each employee's task completions.
-- Generated by the /api/cron/daily-task-report cron at 6 PM PST.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.daily_task_reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  report_date DATE NOT NULL,
  tasks_completed JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- Array of { task_id, title, completed_at }
  tasks_missed JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- Array of { task_id, title }
  total_assigned INTEGER NOT NULL DEFAULT 0,
  total_completed INTEGER NOT NULL DEFAULT 0,
  email_sent BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),

  UNIQUE(user_id, report_date)
);

-- Enable RLS
ALTER TABLE public.daily_task_reports ENABLE ROW LEVEL SECURITY;

-- Admins can do everything
CREATE POLICY "Admins can view all reports"
  ON public.daily_task_reports FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "Admins can insert reports"
  ON public.daily_task_reports FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "Admins can update reports"
  ON public.daily_task_reports FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "Admins can delete reports"
  ON public.daily_task_reports FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Employees can view their own reports
CREATE POLICY "Users can view own reports"
  ON public.daily_task_reports FOR SELECT USING (
    user_id = auth.uid()
  );

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_daily_task_reports_user_date
  ON public.daily_task_reports(user_id, report_date DESC);

CREATE INDEX IF NOT EXISTS idx_daily_task_reports_date
  ON public.daily_task_reports(report_date DESC);

-- ============================================================
-- Ensure completed_at column exists on daily_task_completions
-- (It should already exist with DEFAULT now(), but just in case)
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'daily_task_completions'
      AND column_name = 'completed_at'
  ) THEN
    ALTER TABLE public.daily_task_completions
      ADD COLUMN completed_at TIMESTAMPTZ DEFAULT now();
  END IF;
END $$;
